sudo: required
services:
  - docker

before_install:
  - docker build -t shubhamsingal07/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shubhamsingal07/docker-react npm run test

deploy:
  provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-react"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-west-2-......"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"